/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        bielLight: {
          primary: "#e61558",
          "primary-content": "#fafafa",
          secondary: "#f7aec8",
          "secondary-content": "#3d1a29",
          accent: "#f5f5f5",
          "accent-content": "#1a1a1a",
          neutral: "#0a0a0a",
          "neutral-content": "#fafafa",
          "base-100": "#ffffff",
          "base-200": "#f5f5f5",
          "base-300": "#e5e5e5",
          "base-content": "#0a0a0a",
          info: "#5097fb",
          "info-content": "#fafafa",
          success: "#16a34a",
          "success-content": "#fafafa",
          warning: "#f59e0b",
          "warning-content": "#fafafa",
          error: "#f05a67",
          "error-content": "#fafafa",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
        bielDark: {
          primary: "#f06292",
          "primary-content": "#fafafa",
          secondary: "#6b2843",
          "secondary-content": "#fafafa",
          accent: "#262626",
          "accent-content": "#fafafa",
          neutral: "#fafafa",
          "neutral-content": "#0a0a0a",
          "base-100": "#0a0a0a",
          "base-200": "#262626",
          "base-300": "#333333",
          "base-content": "#fafafa",
          info: "#5097fb",
          "info-content": "#fafafa",
          success: "#16a34a",
          "success-content": "#fafafa",
          warning: "#f59e0b",
          "warning-content": "#fafafa",
          error: "#f05a67",
          "error-content": "#fafafa",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
        },
      },
    ],
    darkTheme: "bielDark",
    base: true,
    styled: true,
    utils: true,
    logs: true,
  },
};

module.exports = config;
